# Generated by Django 2.0.2 on 2018-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180223_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
